language: generic

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - ./setup_couchbase.sh

install: true

after_install:
 - echo "Test Bucket Creation"
 - curl -X POST -u admin:password http://127.0.0.1:8091/pools/default/buckets \
  -d name=newBucket -d ramQuotaMB=100 -d authType=none \
  -d bucketType=ephemeral \
  -d maxTTL=60 \
  -d evictionPolicy=nruEviction
